# Generated by Django 4.2 on 2025-09-24 10:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Fornitore')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codice')),
                ('supplier_type', models.CharField(choices=[('MIDOCEAN', 'Midocean'), ('MAKITO', 'Makito')], max_length=20, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('api_base_url', models.URLField(blank=True, verbose_name='URL Base API')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='API Secret')),
                ('xml_path', models.CharField(blank=True, max_length=500, verbose_name='Percorso File XML')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Ultima Sincronizzazione')),
            ],
            options={
                'verbose_name': 'Fornitore',
                'verbose_name_plural': 'Fornitori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('FULL', 'Completa'), ('PRODUCTS', 'Solo Prodotti'), ('STOCK', 'Solo Magazzino'), ('PRICES', 'Solo Prezzi'), ('MANUAL', 'Manuale')], max_length=20, verbose_name='Tipo Sincronizzazione')),
                ('status', models.CharField(choices=[('PENDING', 'In Attesa'), ('RUNNING', 'In Esecuzione'), ('SUCCESS', 'Completata'), ('ERROR', 'Errore'), ('PARTIAL', 'Parziale')], default='PENDING', max_length=20, verbose_name='Stato')),
                ('products_processed', models.IntegerField(default=0, verbose_name='Prodotti Elaborati')),
                ('products_created', models.IntegerField(default=0, verbose_name='Prodotti Creati')),
                ('products_updated', models.IntegerField(default=0, verbose_name='Prodotti Aggiornati')),
                ('products_errors', models.IntegerField(default=0, verbose_name='Errori Prodotti')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Iniziato il')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completato il')),
                ('error_message', models.TextField(blank=True, verbose_name='Messaggio di Errore')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Dettagli')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Log Sincronizzazione',
                'verbose_name_plural': 'Log Sincronizzazioni',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests_per_minute', models.IntegerField(default=60, verbose_name='Richieste per Minuto')),
                ('requests_per_hour', models.IntegerField(default=1000, verbose_name='Richieste per Ora')),
                ('concurrent_requests', models.IntegerField(default=5, verbose_name='Richieste Simultanee')),
                ('current_minute_requests', models.IntegerField(default=0)),
                ('current_hour_requests', models.IntegerField(default=0)),
                ('last_reset_minute', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reset_hour', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Rate Limit Fornitore',
                'verbose_name_plural': 'Rate Limits Fornitori',
            },
        ),
        migrations.CreateModel(
            name='SupplierEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_type', models.CharField(choices=[('PRODUCTS', 'Prodotti'), ('STOCK', 'Magazzino'), ('PRICES', 'Prezzi'), ('PRINT_DATA', 'Dati Stampa'), ('PRINT_PRICES', 'Prezzi Stampa')], max_length=20, verbose_name='Tipo Endpoint')),
                ('url', models.URLField(verbose_name='URL Endpoint')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('update_frequency', models.IntegerField(default=3600, verbose_name='Frequenza Aggiornamento (secondi)')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo Aggiornamento')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Endpoint Fornitore',
                'verbose_name_plural': 'Endpoint Fornitori',
                'unique_together': {('supplier', 'endpoint_type')},
            },
        ),
    ]
