# Generated by Django 4.2 on 2025-09-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='csv_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Percorso File CSV'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('MIDOCEAN', 'Midocean'), ('MAKITO', 'Makito'), ('BIC', 'BIC')], max_length=20, verbose_name='Tipo'),
        ),
    ]
