# Generated by Django 4.2 on 2025-09-24 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Categoria')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('woocommerce_id', models.IntegerField(blank=True, null=True, verbose_name='ID WooCommerce')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_ref', models.CharField(max_length=100, verbose_name='Riferimento Fornitore')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=500, verbose_name='Nome Prodotto')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('short_description', models.TextField(blank=True, verbose_name='Descrizione Breve')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Brand')),
                ('material', models.CharField(blank=True, max_length=200, verbose_name='Materiale')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Colore')),
                ('dimensions', models.CharField(blank=True, max_length=200, verbose_name='Dimensioni')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso (g)')),
                ('main_image', models.URLField(blank=True, verbose_name='Immagine Principale')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Immagini')),
                ('is_printable', models.BooleanField(default=False, verbose_name='Stampabile')),
                ('print_areas', models.JSONField(blank=True, default=list, verbose_name='Aree di Stampa')),
                ('woocommerce_id', models.IntegerField(blank=True, null=True, verbose_name='ID WooCommerce')),
                ('woocommerce_status', models.CharField(default='draft', max_length=20, verbose_name='Stato WooCommerce')),
                ('last_woo_sync', models.DateTimeField(blank=True, null=True, verbose_name='Ultima Sync WooCommerce')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('supplier_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Aggiornato dal Fornitore')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
                'ordering': ['name'],
                'unique_together': {('supplier', 'supplier_ref')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_variant_ref', models.CharField(max_length=100, verbose_name='Rif. Variante Fornitore')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU Variante')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Colore')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Taglia')),
                ('color_code', models.CharField(blank=True, max_length=20, verbose_name='Codice Colore')),
                ('image', models.URLField(blank=True, verbose_name='Immagine Variante')),
                ('gtin', models.CharField(blank=True, max_length=50, verbose_name='GTIN/EAN')),
                ('woocommerce_variation_id', models.IntegerField(blank=True, null=True, verbose_name='ID Variazione WooCommerce')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Variante Prodotto',
                'verbose_name_plural': 'Varianti Prodotto',
                'unique_together': {('product', 'supplier_variant_ref')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Quantità in Stock')),
                ('reserved_quantity', models.IntegerField(default=0, verbose_name='Quantità Riservata')),
                ('availability_status', models.CharField(default='available', max_length=50, verbose_name='Stato Disponibilità')),
                ('next_arrival_date', models.DateField(blank=True, null=True, verbose_name='Prossimo Arrivo')),
                ('next_arrival_quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantità Prossimo Arrivo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('supplier_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Aggiornato dal Fornitore')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='PrintPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_code', models.CharField(max_length=50, verbose_name='Codice Tecnica')),
                ('technique_name', models.CharField(max_length=200, verbose_name='Nome Tecnica')),
                ('setup_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo Impostazione')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Prezzo Unitario')),
                ('min_quantity', models.IntegerField(default=1, verbose_name='Quantità Minima')),
                ('max_quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantità Massima')),
                ('additional_color_price', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Prezzo Colore Aggiuntivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_prices', to='products.product')),
            ],
            options={
                'verbose_name': 'Prezzo Stampa',
                'verbose_name_plural': 'Prezzi Stampa',
                'ordering': ['technique_name', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Valuta')),
                ('min_quantity', models.IntegerField(default=1, verbose_name='Quantità Minima')),
                ('max_quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantità Massima')),
                ('valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='Valido dal')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valido fino al')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Prezzo',
                'verbose_name_plural': 'Prezzi',
                'ordering': ['min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='PrintOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100, verbose_name='Nome Posizione')),
                ('position_code', models.CharField(max_length=50, verbose_name='Codice Posizione')),
                ('max_width', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Larghezza Max (mm)')),
                ('max_height', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Altezza Max (mm)')),
                ('available_techniques', models.JSONField(default=list, verbose_name='Tecniche Disponibili')),
                ('max_colors', models.IntegerField(default=1, verbose_name='Colori Massimi')),
                ('template_image', models.URLField(blank=True, verbose_name='Immagine Template')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_options', to='products.product')),
            ],
            options={
                'verbose_name': 'Opzione di Stampa',
                'verbose_name_plural': 'Opzioni di Stampa',
                'unique_together': {('product', 'position_code')},
            },
        ),
    ]
