# Generated by Django 4.2 on 2025-09-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mkto_mapping',
            field=models.CharField(blank=True, help_text='Categoria MKTO originale', max_length=200, verbose_name='Mapping MKTO'),
        ),
    ]
